spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hgh_19981886
    url: jdbc:mysql://120.77.242.172/sell?characterEncoding=utf-8&useSSL=false
  redis:
    port: 6379
    host: 120.77.242.172
    
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

projcet-url:
  sell: http://localhost:8080